### ISSUE TITLE
Parameters in config file?

### ISSUE THREAD

**Issue by BrendanTWhite** [nextapps-be/unique-codes#9]
- Package version: n/a
- PHP version: n/a

### Description:
Currently, I believe a developer must specify both primes, plus the list of characters, plus any other parameters they wish to supply, each time they call `UniqueCodes()`. 

I use Laravel and I'd love to be able to put all those config items in a config file, so that I don't need to supply them in the main body of my code.

Does that sound like a good idea? Would the project maintainers be keen to see a PR, if I put one together?

### Steps To Reproduce:
n/a

**Comment by gdebrauwer** [comment]
You are correct, you have to specify all the configuration values each time you want to use the class.

As this package is framework-agnostic, I think the proposed feature would have to be in a separate Laravel package that wraps/extends this package. That wrapper package could then use a Laravel config file so you don't have to provide the configuration manually each time.

**Comment by BrendanTWhite** [comment]
Hi @gdebrauwer 

Ah yes, that makes sense. OK, I might just use the package as-is, but if I do eventually fork it and create a 'laravel-unique-codes' package, I will let you know.

Thanks,
     Brendan.
